calculated_info:
  average_grains_central_penetration[mm]: 0.6227308511734009
  average_grains_volume[mm3]: 0.8084595793601087
  average_radius[m]: 0.1
  grain_volume: 0.8084595799446106
  max_grains_central_penetration[mm]: 0.6227308511734009
  min_grains_central_penetration[mm]: 0.6227308511734009
input_parameters:
  grain_stl_path: ../Resources/Grains/Cuboctahedron.stl
  number_of_grains[-]: 1
  random_seed_number[-]: 0
  save_wheel: true
  template_wheel_number: 4
  wheel_inner_radius[mm]: 99.99
  wheel_outer_radius[mm]: 100.01
